name: Ghost Repo Builder 🦇
on:
  push:
    paths: ['debs/**', 'metadata/**', 'manager.py']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: |
          sudo apt-get update
          sudo apt-get install -y zstd
          pip install zstandard
          python3 manager.py
      - run: |
          git config --global user.name "Ghost Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Auto Rebuild from Dashboard" || exit 0
          git push origin main